name: Upgrader

on:
  workflow_dispatch:
  schedule:
    - cron: "10 2 8 * *"

jobs:
  upgrade:
    uses: browniebroke/github-actions/.github/workflows/poetry-upgrade.yml@v1
    secrets:
      gh_pat: ${{ secrets.GH_PAT }}
